# Generated by Django 5.1.5 on 2025-01-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="apartmentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="images",
                to="Apartments.apartment",
            ),
        ),
    ]
