# Generated by Django 5.1.5 on 2025-01-27 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apartments", "0002_alter_image_apartmentid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="seller",
            field=models.ForeignKey(
                db_column="Apartment_seller",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Apartment_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="apartmentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="Apartments.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="apartmentID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="Apartments.apartment",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="sendUser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
